### ISSUE TITLE
Add a method to babelon for quick machine translation

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/babelon#27]
Options:

- GPT 3.5  or other LLM
- Google Translate
- Other?

Technical:

- translation should be documented as automatic
- perhaps we should indicate in the translated value itself that it was translated by a tool?
- @drseb can help build the context for the prompt to make more precise translations

**Comment by drseb** [comment]
Ah good point regarding provenance: will the license of openAI allow to use those translations?

**Comment by matentzn** [comment]
Yes, no problem

**Comment by matentzn** [comment]
I did that now.
