### ISSUE TITLE
Figure out how we we can use linkml-runtime::csv_loader to parse babel file

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/babelon#5]
https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/loaders/csv_loader.py

- Add that to your CLI
- ideally, this loader should be used, and not pandas

**Comment by matentzn** [comment]
Excellent.

**Comment by hrshdhgd** [comment]
Hey @victoriasoesanto , I ran this locally and it works if you first convert the `cdv` into `tsv`. Not sure if this is a bug but that will get you past this error. Hope this helps!

**Comment by victoriasoesanto** [comment]
@hrshdhgd That works! Thank you so much. @cmungall would this be a bug?

**Comment by cmungall** [comment]
Yes you can go ahead and make separate issues:

- feature request: infer delimiter from filename if not explicitly specified
- general issue: provide more informative reporting. E.g. if the TSV is parsed to have a single column this is likely a delimiter mismatch

I'll close this one as it looks like you have it working

**Comment by victoriasoesanto** [comment]
Thank you @cmungall .
